version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: telegrambot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  telegram-bot:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
