version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: telegrambot_46oc
      POSTGRES_USER: nikita
      POSTGRES_PASSWORD: dt0FyAUDyBJcSm7jstZYG5skGWqx1C6b
    ports:
      - "5432:5432"

  telegram-bot:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
